# Generated by Django 4.0.6 on 2022-08-06 08:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_category_alter_news_create_at_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 6, 8, 41, 55, 126559, tzinfo=utc)),
        ),
    ]
