# Generated by Django 4.0.6 on 2022-08-11 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_category_title_alter_news_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
